### PR TITLE
Added script to publish API docs up to github pages

### PR DESCRIPTION
**Pull request by jasperblues**
Script requires: 
- The two added files
- Appledoc installed 
- Ant tool (available via mac ports)
- gh-pages branch created - you can do this via github console or just create and push a branch called gh-pages

Then run: ant

. . . reports are pushed up to gh-pages. . .. edit your README to link to the reports. . . (Example in my fork). 

This script can be called by a build server like Bamboo or Jenkins to publish latest docs after every build. . . .

### CODE REVIEW

**Comment by biasedbit** [comment]
Any chance we can roll the build files under the `Project/` directory?

**Comment by jasperblues** [comment]
Sure they could be tucked out of the way there. . . 

Btw: Script is a cutdown version of a full ci build script. (Tests, code coverage. Etc)

New pull req coming

**Comment by jasperblues** [comment]
Moved the docs-gen scripts to the Project dir, as requested. . . 

Alternatively, if you push to the main CocoaPods repo, you could also link to the docs here: http://cocoadocs.org/

**Comment by biasedbit** [comment]
It's only showing this change for me:



Maybe you forgot to add the files on the new folder?

**Comment by jasperblues** [comment]
Oops i did forget. . . . fixed.

**Pull request merged**
